version: "3.8"
networks:
  mynet:
    driver: bridge
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - SERVERURL=<secret>
    - SERVERPORT=51820
    - PEERS=3
    - PEERDNS=auto
    - ALLOWEDIPS=0.0.0.0/0
    ports:
    - "51820:51820/udp"
    volumes:
    - /home/pi/IOTstack/volumes/wireguard:/config
    - /lib/modules:/lib/modules:ro
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
    
  prometheus-wireguard-exporter:
    network_mode: host
    container_name: wgexporter
    restart: unless-stopped
    image: mindflavor/prometheus-wireguard-exporter
    volumes:
    - ./config:/config
    - /lib/modules:/lib/modules:ro
    command:
    - '--prepend_sudo=true'
    cap_add:
    - NET_ADMIN
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - mynet